package com.aibles.iam.shared.error

import org.springframework.http.HttpStatus

enum class ErrorCode(val httpStatus: HttpStatus) {
    BAD_REQUEST(HttpStatus.BAD_REQUEST),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    FORBIDDEN(HttpStatus.FORBIDDEN),
    CONFLICT(HttpStatus.CONFLICT),
    VALIDATION_ERROR(HttpStatus.UNPROCESSABLE_ENTITY),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    RATE_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    USER_EMAIL_CONFLICT(HttpStatus.CONFLICT),
    USER_DISABLED(HttpStatus.FORBIDDEN),
    GOOGLE_TOKEN_INVALID(HttpStatus.UNAUTHORIZED),
    PASSKEY_NOT_FOUND(HttpStatus.NOT_FOUND),
    PASSKEY_COUNTER_INVALID(HttpStatus.UNAUTHORIZED),
    PASSKEY_CHALLENGE_EXPIRED(HttpStatus.BAD_REQUEST),
    PASSKEY_ATTESTATION_FAILED(HttpStatus.BAD_REQUEST),
    TOKEN_INVALID(HttpStatus.UNAUTHORIZED),
    TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED),
    TOKEN_REVOKED(HttpStatus.UNAUTHORIZED),
}
